###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root-secret
            - MYSQL_DATABASE=${SQL_DATABASE}
            - MYSQL_USER=${SQL_USERNAME}
            - MYSQL_PASSWORD=${SQL_PASSWORD}
        ports:
            - '${SQL_PORT_EXTERNAL}:${SQL_PORT}'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${WEB_PORT}:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
