#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/..

if [[ $# -eq 0 ]]; then
	docker compose exec --user developer php-fpm bash
else
	docker compose exec --user developer php-fpm "$@"
fi
