#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/..

if test -f /.dockerenv; then
    echo 'run this script outside docker'
    exit 1
fi

ENVIRONMENT_FILES="--env-file docker.env.dist --env-file docker.env"

if test "$1" = "root"; then
    docker compose $ENVIRONMENT_FILES exec php-fpm bash
elif test "$1" = "database"; then
    docker compose $ENVIRONMENT_FILES exec mysql bash
elif test "$#" -eq 0; then
    docker compose $ENVIRONMENT_FILES exec --user developer php-fpm bash
else
    docker compose $ENVIRONMENT_FILES exec --user developer php-fpm "$@"
fi
