#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/..

docker compose up --detach --remove-orphans
docker compose stop
docker compose rm --force
docker system prune

. $SCRIPT_DIR/setup --no-cache
