#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/..

ENVIRONMENT_FILES="--env-file docker.env.dist --env-file docker.env"

docker compose $ENVIRONMENT_FILES stop
docker compose $ENVIRONMENT_FILES rm --force
docker system prune

rm -rf ./vendor

. $SCRIPT_DIR/setup --no-cache
. $SCRIPT_DIR/server --remove-orphans
