#!/usr/bin/env bash

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR/..

echo -e 'Updating composer packages\n'
./script/console composer install

# Add commands for:
# - npm install
# - database migrations
# - other build processes
